"""empty message

Revision ID: 6ebb7f0de6c7
Revises: 9edd6354c302
Create Date: 2022-06-01 17:54:43.768669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebb7f0de6c7'
down_revision = '9edd6354c302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lecture', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lecture')
    # ### end Alembic commands ###
