"""init

Revision ID: b95dacb2669e
Revises: 
Create Date: 2022-05-13 10:16:40.718688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95dacb2669e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learneds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.Column('custom_lecture_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learneds_id'), 'learneds', ['id'], unique=False)
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_code', sa.String(length=6), nullable=False),
    sa.Column('lecture_name', sa.String(length=40), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('semester', sa.String(length=10), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('major', sa.String(length=20), nullable=False),
    sa.Column('credit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectures_id'), 'lectures', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=8), nullable=False),
    sa.Column('major', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lectures_id'), table_name='lectures')
    op.drop_table('lectures')
    op.drop_index(op.f('ix_learneds_id'), table_name='learneds')
    op.drop_table('learneds')
    # ### end Alembic commands ###
