"""user_lecture

Revision ID: e010a58e2115
Revises: 6ebb7f0de6c7
Create Date: 2022-06-01 18:14:53.370557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e010a58e2115'
down_revision = '6ebb7f0de6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lecture')
    op.add_column('users', sa.Column('basic_lecture', sa.BLOB(), nullable=True))
    op.add_column('users', sa.Column('major_lecture', sa.BLOB(), nullable=True))
    op.add_column('users', sa.Column('research_lecture', sa.BLOB(), nullable=True))
    op.add_column('users', sa.Column('free_select_lecture', sa.BLOB(), nullable=True))
    op.add_column('users', sa.Column('non_credit_lecture', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture', sa.BLOB(), nullable=True))
    op.drop_column('users', 'non_credit_lecture')
    op.drop_column('users', 'free_select_lecture')
    op.drop_column('users', 'research_lecture')
    op.drop_column('users', 'major_lecture')
    op.drop_column('users', 'basic_lecture')
    # ### end Alembic commands ###
